### ISSUE TITLE
Report processing incorrectly processes subsequent months of data

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#107]
Report processing incorrectly processes subsequent months of data.  The file being downloaded is the same name for each billing period and our current download/process implementation will use the last cursor position of the previous month on the current month.  This will lead to the current month's data being incompletely processed.  It is resuming from last months cursor when it should be starting from 0 since it's a new file.

**Comment by chambridge** [comment]
Should we be storing the assemblyID instead of the filename or some combination?
