### ISSUE TITLE
Clean up temporary CUR files after processing completes

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#141]
**Describe the bug**
As CURs are downloaded and processed they are placed on a shared volume in a temp directory. The temp directory is never cleaned up so eventually depending on the number of providers and updates from AWS this volume can run out of space.

**To Reproduce**
1. Run masu download with multiple providers that have CUR reports which will expand to greater than the shared drive size over time.

**Expected behavior**
We should clean up files after we have completed processing them to retain space in the shared volume.

**Comment by dccurtis** [comment]
I'll take this one.  Had it on my radar when I was doing the temp file changes
