### ISSUE TITLE
On container startup, worker MainProcess ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/masu#155]
On boot, every worker has a ConnectionResetError at the beginning of the log with the traceback below. The worker still connects to rabbitmq immediately after and works normally but it's always present.

[2018-08-22 18:49:13,508: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq.hccm-master.svc:5672//
--
  | [2018-08-22 18:49:13,567: INFO/MainProcess] mingle: searching for neighbors
  | [2018-08-22 18:49:13,574: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 322, in start
  | blueprint.start(self)
  | File "/opt/app-root/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
  | step.start(parent)
  | File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 40, in start
  | self.sync(c)
  | File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 44, in sync
  | replies = self.send_hello(c)
  | File "/opt/app-root/lib/python3.6/site-packages/celery/worker/consumer/mingle.py", line 57, in send_hello
  | replies = inspect.hello(c.hostname, our_revoked._data) or {}
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/control.py", line 143, in hello
  | return self._request('hello', from_node=from_node, revoked=revoked)
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/control.py", line 95, in _request
  | timeout=self.timeout, reply=True,
  | File "/opt/app-root/lib/python3.6/site-packages/celery/app/control.py", line 454, in broadcast
  | limit, callback, channel=channel,
  | File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 315, in _broadcast
  | serializer=serializer)
  | File "/opt/app-root/lib/python3.6/site-packages/kombu/pidbox.py", line 290, in _publish
  | serializer=serializer,
  | File "/opt/app-root/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
  | exchange_name, declare,
  | File "/opt/app-root/lib/python3.6/site-packages/kombu/messaging.py", line 203, in _publish
  | mandatory=mandatory, immediate=immediate,
  | File "/opt/app-root/lib/python3.6/site-packages/amqp/channel.py", line 1732, in _basic_publish
  | (0, exchange, routing_key, mandatory, immediate), msg
  | File "/opt/app-root/lib/python3.6/site-packages/amqp/abstract_channel.py", line 50, in send_method
  | conn.frame_writer(1, self.channel_id, sig, args, content)
  | File "/opt/app-root/lib/python3.6/site-packages/amqp/method_framing.py", line 166, in write_frame
  | write(view[:offset])
  | File "/opt/app-root/lib/python3.6/site-packages/amqp/transport.py", line 275, in write
  | self._write(s)
  | ConnectionResetError: [Errno 104] Connection reset by peer

**To Reproduce**
1. Deploy koku, masu, rabbit normally
2. When the worker pods is starting, view the log

**Expected behavior**
Even though the worker operates normally, the exception being thrown at start may indicate that a bad setting is enabled or misconfigured.

**Context (please complete the following information):**
 - OS: OpenShift Dedicated
 - Masu Commit: 28c2a46

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
