### ISSUE TITLE
Update the AWS Bill DB row when bill is finalized

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#168]
## User Story
As a user of HCCM, I want my reported data to be accurate so that I can make reliable judgements on my data. As a developer, I want summary table data to get reprocessed for a billing period when the bill is finalized. That summary task relies on the bill being marked as finalized in the database.

## Impacts
Backend

## Assumptions
-- Once the bill is marked as summarized the summary update task will rerun the billing period in its entirety

## Acceptance Criteria

- [ ] Finalized data is accurately reflected in the summary tables

**Comment by adberglund** [comment]
This should be handled by regular processing now. Will keep open until we've seen a month boundary clear and everything work.

**Comment by lcouzens** [comment]
Verified
Commit: 0b677cc6373d1fb1b29da99d9a06a76b26865799
