### ISSUE TITLE
Create OpenShift templates to support Celery using RabbitMQ

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#18]
In order to support multiple workers processing customers cost usage reports we will be leveraging [Celery](https://www.fullstackpython.com/celery.html). Celery can utilize several different brokers, the most popular is RabbitMQ.

This deployment into OpenShift needs to be templated to enable the correct function of the application.

____
Associated with https://github.com/project-koku/masu/issues/6

**Comment by blentz** [comment]
Looks like someone might already have done 80% of the work for us... 

https://github.com/redhat-cop/containers-quickstarts/tree/master/rabbitmq
