### ISSUE TITLE
Make initial data ingest configurable for when adding a new provider.

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#181]
Today Masu will ingest only the current month's data when a new provider is added.  We need to make the number of months for initial data ingest to be configurable.

Acceptance Criteria:
* Environment variable is available to specify how many previous months of data should be initially ingested when adding a provider.  Default value can be discussed for only a handful of internal users we could probably set it to 2 months.
* Only current month data is downloaded/processed after the initial ingest

**Comment by dccurtis** [comment]
PRs related to this:
Koku: https://github.com/project-koku/koku/pull/366
Masu: https://github.com/project-koku/masu/pull/204

**Comment by lcouzens** [comment]
Verified
"commit": "6143cb9cd6eab9d91c5604071877041bcea89765"
