### ISSUE TITLE
Handle Insights message service notification for new OCP reports

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#196]
## User Story
As the Data Processor, I want the Insights Platform Message Queue to notify me whenever a new Operator Metering report package has been uploaded

## Impacts
Data Processor

## Role
Backend Service

## Assumptions
- We know the Insights Account associated with the uploaded package.
- We will have a identifier that will allow us to validate the uploaded report package

## Implementation Details
- We will validate that the data provided through the Upload Service is of a valid format to be processed
- If package is valid work will be queued up to download the report package

## Acceptance Criteria

- [ ] Verify that the data processor unpacks the package and validates the format of the report data

- [ ] Verify that the data process queues up work to download the package

**Comment by dccurtis** [comment]
Work was done as part of #234

**Comment by lcouzens** [comment]
Verified
commit: "191e4cce6ded23532d5f46573ada2fea8e627404"
