### ISSUE TITLE
Consume operator metering usage reports

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#198]
## User Story
As a user, I want the OCP Operator Metering usage reports to consumed by the cost management service

## Impacts
Data Processor

## Role
Backend Service

## Assumptions
- Operator Metering usage reports have been validated and are available in the Upload Service object store
- We know the Insights Account associated with the uploaded package.
- We will have a identifier that will allow us to obtain the usage reports

## Implementation Details
- Given the identifier we will download the usage reports from the upload service object store
- Queue up work to process the usage and calculate the cost

## Acceptance Criteria

- [ ] Verify that the usage report is download by the data processor
- [ ] Verify that work has been queued to process the data and calculate the cost

**Comment by dccurtis** [comment]
Work completed with OCP-local provider.

https://github.com/project-koku/masu/pull/224

This PR will download OCP-local files and process them.

**Comment by lcouzens** [comment]
Verified
"commit": "79267e27f71d8818fcc3b6ff584137a33f1e058c"
