### ISSUE TITLE
Cost Usage Data Expiration (3 months)

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#20]
## User Story
As service, I want to expire customer cost usage data that is older than 3 months so that our database & table size is limited and performance improved rather than keeping data for all time.

The expiration should be a configurable amount with 3 months as a default, but as we move beyond the first release we can contain more data. 

Data expiration should happen on month boundries, it should not delete data on a rolling 3 months from now basis.

## Impacts
Dev

## Assumptions
We can wake up workers on a regular basis and prune data from the data base

## Implementation Details
When each new month hits we should be able to remove any data that is 4 months or older

## Acceptance Criteria

- [ ] Data is removed on a monthly basis for data that is 4 months or older.

**Comment by dccurtis** [comment]
This functionality was checked in under several PRs (including some tooling and bug fixes).  Reviewing the functional tests done for each PR might be helpful in understanding how to test:

https://github.com/project-koku/masu/pull/109: Internal database related changes (nothing external to verify)

https://github.com/project-koku/masu/pull/116: Synchronously deleting expired data (Added `/api/v1/expired_data` endpoint to view and remove expired data

https://github.com/project-koku/masu/pull/119: Asynchronously deleting expired data (Same as #116 only now the deletion happens in celery workers.  Need to now include `remove_expired` queue if running rabbit workers locally

https://github.com/project-koku/masu/pull/122: Continuation of #119 only now expired data queuing happens once a month.  The day of the month can be configured via an environment variable but defaults to the first of the month at midnight.

https://github.com/project-koku/masu/pull/124: Performance optimization (nothing external changed other than log messages)


Tooling needed to setup environment and verify (historical data load by changing masu system date):
https://github.com/project-koku/masu/pull/106

Bug fixed as a result of this work:
https://github.com/project-koku/masu/pull/110
