### ISSUE TITLE
Summarize the OCP cost and usage data

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#201]
## User Story
As a user, I want the OCP cost entries to be summarized for improved performance when queried.

## Impacts
Data Processor

## Role
Backend Service

## Assumptions
- N/A

## Implementation Details
- As cost usage line entries are created from hourly usage data we can generate aggregate data based information

## Acceptance Criteria

- [ ] Verify that the summarized aggregate data matches the raw usage cost line entries

**Comment by lcouzens** [comment]
Verified
"commit": "6143cb9cd6eab9d91c5604071877041bcea89765"
