### ISSUE TITLE
Simulate Insights messaging service notification of new OCP usage reports

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#202]
## User Story
As a service developer/quality engineer, I want the to be able to simulate receiving a notification from the Upload Service for a new OCP report package via a test endpoint

## Impacts
Data Processing

## Role
Service Developer / Quality Engineer

## Assumptions
- We can simulate the notification via Messaging Service of a new package in the Upload Service to process

## Implementation Details
- Expose a test API endpoint that can drive the notification of a new OCP report package for download and processing

## Acceptance Criteria

- [ ] Verify that download and processing is triggered via the Message Queue simulation endpoint

**Comment by dccurtis** [comment]
Simulation turned out to not be necessary.  A local instance of the Upload service is available and should be used for all local development.  Any download/processing related work can be done by populating the `/var/tmp/insights_local` directory with appropriate .csv and manifest.json files.
