### ISSUE TITLE
Allow the customer to specify the name of the files used in Koku

### ISSUE THREAD

**Issue by chargio** [project-koku/masu#213]
## User Story
As a user, I want to reuse existing configuration for accessing CUR files in the AWS account (i.e the user is using files for an internal usage or for a third party tool). In order to do so, the options for prefix and suffix should be available.

## Impacts
Configuration and naming for files.
Documentation.

## Role
Admin

## Assumptions
-
-

## Implementation Details
-
-

## Acceptance Criteria

- [ ]
- [ ]

**Comment by chambridge** [comment]
@chargio Are you sure this doesn't already work. I believe @dccurtis already made changes to support report prefixes.

I'm not clear what you are looking for in terms of changes here. We are specific in our docs to limit a new user opportunity for mistakes. If you are looking for more specific changes could you please clarify? The above issue doesn't provide enough information to clearly understand the problem to be solved.

**Comment by chargio** [comment]
The documentation and the interface does not allow you to specify any of those parameters. If it is possible UI and docs should be updated.

**Comment by chambridge** [comment]
Providing prefixes, etc. are all done on the Amazon side. You don't need to specify this for our consumption. We get the name of the CUR from Amazon when we ask for the current report definition.

**Comment by chargio** [comment]
So even if you define a folder for the data + prefix and suffix it will continue working? Because the names of the files will change in that case.

**Comment by chambridge** [comment]
@dccurtis can confirm, but yes I believe everything is working. Have you encounter a case where it is not.

**Comment by dccurtis** [comment]
We support report prefixes today, as @chambridge mentioned, it's all configured on the AWS side.  Masu has the ability to find the correct manifest and cur files based on a response from AWS indicating the configured report name and prefix (if one is set).
