### ISSUE TITLE
Add provider_id and DELETE call for report data

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#230]
## User Story
As a data admin I'd like to associate report data with a provider so that it can be removed when the provider is removed.

## Impacts
DB, API

## Implementation Details
- Add provider_id to the AWS cost usage bill
- Add a DELETE report_data API to remove provider data

## Acceptance Criteria

- [ ] report_data DELETE removes all report data for a provider
- [ ] provider_id is in the report bill

**Comment by lcouzens** [comment]
Verified
"commit": "9e68a3987b29a6388ba576ae4ad87e6e43200cc6"
