### ISSUE TITLE
Create Admin tooling

### ISSUE THREAD

**Issue by blentz** [project-koku/masu#24]
## User Story
As a service administrator, I want a tool that reports the health of Masu so that I know whether my service is healthy or broken.

## Impacts
CLI or API

## Role
Service Administrator

## Assumptions
- This tool will only be available to service admins, not customers. (i.e. don't redact data or require additional auth)
-

## Implementation Details
- If the tool is a CLI tool, no auth is needed. If the tool exposes data via the API, auth may be needed.
- The tool may use subcommands to report on different pieces of data. (e.g. in the case of a CLI tool,`$ masu status` could report service state and `$ masu report` could report service-wide job statistics.

## Acceptance Criteria

- [ ] The tool reports on the number of jobs attempted, succeeded, and failed, from Masu's perspective.
- [ ] The tool reports the status of its connection to other services (e.g. Koku DB, RabbitMQ brokers, etc.)
- [ ] (optional) The tool may report additional details about failures (e.g. last 5 log lines, counts of most common errors, etc.)

**Comment by adberglund** [comment]
Just found this for celery status check https://stackoverflow.com/questions/8506914/detect-whether-celery-is-available-running

**Comment by dccurtis** [comment]
Another health or status check that came to mind is one where we monitor the free space available in our CUR file temporary storage location.  If the persistent volume runs out of space we will not be able to continue.

**Comment by LandoCalrizzian** [comment]
VERIFIED
