### ISSUE TITLE
Recalculate charge based on changes to the price list within a month

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#260]
## User Story
As user, I want my charges for the month to be recalculated if changes are made during the month so that the reflected charges match the "current" price list.

## Impacts
Backend

## Role
User

## Implementation Details
Endpoint to trigger charge recalculation within a month.

## Acceptance Criteria

- [ ] Updates to a price list trigger the charges to be recalculated

---
Related to:
https://github.com/project-koku/koku/issues/468

**Comment by blentz** [comment]
I really don't think this is the mechanism that we want. We don't want to trigger a huge amount of DB churn every time someone edits a price. That isn't going to scale at all.

I think we need to think about what we want here before we implement it.

**Comment by chambridge** [comment]
We could also do a look up the next time we are processing new data to see if any rate changes occurred during the window of the previous processing and if so expand the summarization from 3 day window to the full month. That would avoid us kicking off triggers while a user is actively making multiple edits to rates and just slightly alter what was going to take place anyways during normal processing flow.

**Comment by chambridge** [comment]
This doesn't match our most recent discussion of the price list features. Closing this to remove confusion.
