### ISSUE TITLE
Summary data is not removed when expired data is removed.

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#274]
AWS and OCP summary and aggregate table data is not removed when expired report data is removed.  The impact of this is that report data will still be visible on the Koku API even after a provider has been removed or the data has exceeded masu's report expiration date.

**Comment by adberglund** [comment]
- Hurdle around AWS provider to data match up.
- Delete should remove all data.
Sergio:
- Have ability to disable provider instead of delete (this is in the realm of Sources, not necessarily cost management)
  - No new data, but keep data that is there

**Comment by lcouzens** [comment]
It would be awesome to have some traction on this, we have a number of automation tests that require a clean database each time to prevent failures. Though we can use the re-summarization endpoint that has its own issues when trying to run it to clean up all provider data, I think its some issue with needing to have at least one provider to be able to re-summarize data.

**Comment by lcouzens** [comment]
Verfied
Commit: 27cf79ead6b17456269a62ee7a502a3725924e54
