### ISSUE TITLE
Optimization of units when ingestion

### ISSUE THREAD

**Issue by chargio** [project-koku/masu#28]
## User Story
As a user, I want to be able to define the storage unit. Different providers use different units for providing information.  Some uses bytes, some Mb, some Gigibytes. Those units should be identified and stored, in case they change in the future.

## Impacts
Data ingestion

## Implementation Details
- Make sure we are storing the unit name (e.g. GB) in a column in the database alongside the value
-

## Acceptance Criteria

- [ ] Information is stored with a known unit
- [ ] Information from different providers can be normalized
- [ ] When information is in different ranges (i.e. Tb vs b), it still can be used without losing details.
- [ ] If the information changes (i.e. a provider was providing Mb and now strat providing Gb), we can adapt to it

**Comment by chambridge** [comment]
For *Release 1* we will only need to focus on storage.

**Storage:**
Standardize on Gb

**Comment by chargio** [comment]
GB, not Gb... That is why this is needed

**Comment by blentz** [comment]
So, this needs a few pieces:

1. Utility functions for unit conversions. There's likely a pre-existing library to do this.
2. Storing report data in a single, consistent set of units.
3. Storing the units for each data point.
4. API query facilities to request data in a particular base unit.

**Comment by chargio** [comment]
https://github.com/ManageIQ/manageiq-consumption/tree/master/app/helpers/manageiq/showback

Helpers to do currency conversion (in case there is no standard library that does that)

Look for tests to see how it is used

**Comment by adberglund** [comment]
We have decided at this point that we won't change any units during ingestion. In the AWS Cost Usage Report case, many of the fields are interdependent and altering usage values to convert units would mean we'd have to recalculate rates, and possibly pricing values too. 

We decided it would be best to focus our efforts on unit conversion when presenting data in the UI, which is being tracked in project-koku/koku#203. 

We do have a question out to AWS to confirm the units used for various usage values so we can know definitely what units we're starting from when we decide to convert in the API/UI later on.

**Comment by chargio** [comment]
Do we store the unit in the database or we rely on knowing what is it?

**Comment by adberglund** [comment]
@chargio Ideally we store a mapping for usage type to reported unit in the database. I'm not getting great feedback from AWS that such a thing exists. For now we are replying on the unit reported in the pricing columns to be the unit being used. We are currently storing that.

**Comment by adberglund** [comment]
For now I think we need to rely on the units we're pulling from the product table, as we are currently doing. AWS basically said that no universal mapping exists to verify units used as each service owns the information for their own service.
