### ISSUE TITLE
Tier charge calculation should include all applicable rates within the tier

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#281]
## User Story
As a user, I want OCP charge calculations to be a summation of all applicable tier rates for my memory or cpu usage.

For example:
```
Usage = 25
Tier = [{usage_start_gt = 0, usage_end_lte = 10, rate = 0.10},
            {usage_start_gt = 10, usage_end_lte = 20, rate = 0.20},
            {usage_start_gt = 20, usage_end_lte = 30, rate = 0.30},
            {usage_start_gt = 30, rate = 0.40}]
```
Charge =10 * 0.10 + 10 * 0.20 + 5 * 0.30 = 4.5

## Impacts
API, Docs

## Role
User

## Assumptions
- Tier rates will cover the entire spectrum of usage. Tiers will have a convention similar to the example where the lower bound is > and the upper bound is <=

## Acceptance Criteria

- [ ] CPU or Memory charge is calculated based on the example provided, where the usage is the larger of the respective usage and request values.

**Comment by chargio** [comment]
Look good to me
