### ISSUE TITLE
Summarize OCP charge data by tag keys

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#285]
We need to be able to group OCP charge data by tag key. The data needs to be summarized on a daily and monthly basis for the last 10 days, 30 days, current month and previous month.

Tag keys have similar time scope.

We need to be able to perform partial matches within the tag values
filter[environment]=dev
would find any tag with key=environment and containing value _dev_ such that it would match development and dev and develop, etc.

**Comment by lcouzens** [comment]
Verified
commit: 0ce1865c4ed6dc95b87e1d74c02eebb836fb570b
