### ISSUE TITLE
Summarize AWS cost data by tag keys

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#287]
We need to be able to group AWS cost data by tag key. The data needs to be summarized on a daily and monthly basis for the last 10 days, 30 days, current month and previous month.

Tag keys have similar time scope.

We need to be able to perform partial matches within the tag values
filter[environment]=dev
would find any tag with key=environment and containing value dev such that it would match development and dev and develop, etc.

**Comment by lcouzens** [comment]
Verified
Commit: b7bca99add93d0bef63ad849a29de3da1b95d96e
