### ISSUE TITLE
Charge by OCP Storage metrics

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#348]
## User Story
As user, I want my rate for storage usage/request of OCP data to be applied so that I can see reports with costs based on storage consumption.

## Impacts
UI, Docs

## Role
User

## Assumptions
- Metrics for storage usage/request

## Implementation Details
- Apply storage rates based on usage and request to the processed OCP data

## Acceptance Criteria

- [ ] Rate is applied to OCP storage data based on usage and/or request based on definition 
- [ ] Rate of 0 is applied if no storage rate exists for that provider

____
Associated with: https://github.com/project-koku/masu/issues/347

**Comment by chargio** [comment]
What are the alternatives?

Why can't we calculate this? What are the limitations we have?
I see that AWS prices like this: TimedStorage-ByteHrs for S3 and $0.10 per GB-month of General Purpose SSD (gp2) provisioned storage - US East (Northern Virginia) (for instance)

Some other charges are monthly (i.e. $0.005 per 1,000 PUT, COPY, POST, or LIST requests)
So actually we have both, and both are related to the monthly charges


First 50 TB / Month | $0.023 per GB
-- | --
Next 450 TB / Month | $0.022 per GB
Over 500 TB / Month | $0.021 per GB

@blentz It would be great to know about your experience here.

**Comment by chambridge** [comment]
@chargio I'm not trying to suggest alternatives, I'm trying to clarify the requirement for implementation.

Seems like `GiB per month` should be the focus of our first implementation.

I didn't say we couldn't calculate it, it comes down to the strategy for the implementation.

Currently for CPU and memory the rate is hourly so the math for the calculation of charge is simple and can be done in the normal flow of processing the usage data.

With operator metering data we are going to be dealing with EBS (or the like storage).

AWS explains [EBS pricing](https://aws.amazon.com/ebs/pricing/) as follows:
> For example, let's say that you provision a 2000 GB volume for 12 hours (43,200 seconds) in a 30 day month. In a region that charges $0.10 per GB-month, you would be charged $3.33 for the volume ($0.10 per GB-month * 2000 GB * 43,200 seconds / (86,400 seconds/day * 30 day-month)).

So I think we are still able to do this in `masu` if the same strategy can be taken. I just want agreement on the calculation of charge.
