### ISSUE TITLE
Correlate AWS costs with OCP usage for EC2 instances

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#349]
## User Story
As user, I want to understand the cost of running OCP on AWS using the cost data from AWS EC2 instance used to run OCP so that I can see my breakdown for OCP by project, node, cluster.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- OCP resource_id column provides the EC2 instance name for correlation
- Cost will be distributed via some combination of usage/request metrics (cpu/memory)

## Implementation Details
- When processing an AWS provider look for the ability to process OCP cost distribution. Either by scanning existing OCP tables for resource_id that match AWS instances or by looking at a new table to be used to correlate OCP and AWS (may include things like tags in the future).

- New tables will exist that duplicate AWS schema but also add "cluster", "node", "project" columns.

- When processing line items, only EC2 instance line items that correlate to OCP nodes will be added to the new OCP on AWS tables. The EC2 instance line items will be broken down to reflect the pod usage/request distribution formula. Entries created for each pod will include the "cluster", "node", "project", and "tag" data from that pod. Un-utilized percentage of the instance will get an entry with the "cluster" and "node" information.

## Acceptance Criteria

- [ ] Tables similar to AWS only will be created in a schema with additional columns with the "cluster", "node", and "project" information.
- [ ] Line items with EC2 instance data that match the OCP resource_id will make up the contents of the OCP on AWS tables broken down by utilization formula
- [ ] OCP on AWS tables will be aggregated for breakdown on existing daily and monthly time scopes
- [ ] Only 3 months of raw data will be kept for the OCP on AWS data

**Comment by chambridge** [comment]
Processing of OCP on AWS data can use the daily aggregate tables instead of hourly as we still have the detail level of pod usage.

**Comment by chambridge** [comment]
For first phase cost distribution will be using CPU usage.

**Comment by blentz** [comment]
I've put together a simple/naive weighted cost distribution formula here: https://docs.google.com/document/d/1EnvX-4kG-0xbX7PB-byWbCqbUhw3RJ8h0e-nCiGMVHM/edit?usp=sharing

It should result in a more "fair" final cost based on relative consumption of multiple resources.

**Comment by adberglund** [comment]
Testing this will require nise static data generation where both OCP and AWS files share the same resource_id

**Comment by lcouzens** [comment]
Verified
Commit: 6fb2ef11bb48542ce26b5011d30a29bac526e5be
