### ISSUE TITLE
Correlate AWS costs with OCP usage by tags

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#352]
## User Story
As user, I want to understand the cost of running OCP on AWS using the cost data from AWS line items with tags correlated with OCP labels from operator metering reports so that I can see my breakdown for OCP by project, node, cluster.

## Impacts
API, UI, Docs

## Role
User

## Assumptions
- We will use the resolution from the tag mapping investigation: https://github.com/project-koku/masu/issues/338
To assume special AWS tag keys, `ocp_cluster`, `ocp_node`, and `ocp_project`, to correspond to the OCP objects cluster, node and project. All other tags will use an case-insensitive match.
- The user is required to add tags for correlation to both OCP resources (except for cluster, node, project) and AWS billing line items.
- If an AWS line item has multiple `ocp_project` tags (or other OCP objects with the special tag keys) the cost of the line item will be evenly distributed across those items (e.g. RDS service line item with 4 `ocp_project` tags will be split evenly 4 ways (naively assuming equal usage)

## Implementation Details
- As daily aggregated data is processed correlate tags in OCP (plus cluster, node, project) with tags on the AWS entry.
- Distribute the cost evenly across like OCP objects.

## Acceptance Criteria

- [ ] Correlation occurs between tag key an values of different case across OCP and AWS
- [ ] Special AWS tags for OCP objects are correctly mapped to OCP objects
- [ ] If an AWS line item has multiple OCP object tags the cost is evenly distributed across them

**Comment by chargio** [comment]
This will be a fine advancement.

We will need to open a new issue for a later sprint where costs are distributed differently:
- If base metrics and capacity exists, distribute using that (i.e. CPU of project vs CPU capacity of cluster)
- If not, use this strategy

**Comment by chambridge** [comment]
ocp_project --> openshift

**Comment by lcouzens** [comment]
Verified
Commit: 4d67ef8cbc2f2a3c5dd0ff2505551903631d8620
