### ISSUE TITLE
OCP data without labels is not being summarized

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#354]
Report data is only being summarized if the line item contains a pod_label.  The root cause is because `jsonb_each_text` is dropping the data in the daily table SQL query.

**Comment by adberglund** [comment]
To test this, OCP data should be generated without tags, and totals should add up in the koku API.

**Comment by lcouzens** [comment]
Verified
Commit: 480d5fddb3d5a0c164f186a4f2034122afbb008b
