### ISSUE TITLE
Calculate OCP storage metric charge from variable rate tiers

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#372]
## User Story
As user, I want OCP charge calculation for storage usage/request of OCP data to be be calculated based on variable rate tiers.

## Impacts
UI, Docs

## Role
User

## Assumptions
- Metrics for storage usage/request
- Development is in sync with @chargio on how the tiered calculation should work.  See conversation in #348 for some background.

## Acceptance Criteria

- [ ] Tiered rate is applied to OCP storage data based on usage and/or request based on definition 
- [ ] Rate of 0 is applied if no storage rate exists for that provider

____
Associated with: https://github.com/project-koku/masu/issues/348

**Comment by dccurtis** [comment]
No changes are needed since all units line up and the existing variable rate logic still holds.

Verified end-to-end
1.  Generate storage report that's easy to examine charges
2.  Add OCP Provider
3.  Add usage and request storage tiered rates

**Comment by lcouzens** [comment]
Verified
Commit: 3da7031fae2cf0eb8e422a352e18870fe64a0aa9
