### ISSUE TITLE
Capture provider processing state in prometheus metrics

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#396]
## User Story
As a service operator, I want to capture the various provider processing states as counts, times, error_counts, so that I can understand the state of processing and build alerts for issues within the system

## Impacts
Backend

## Role
Service Operator

## Assumptions
- Will register service with prometheus annotations to get read by the platform prometheus component.

## Implementation Details
Will need to surface an http server on masu_worker that can report `/metrics` for prometheus to consume.

Will update openshift template with service and prometheus annotation.

Need to add https://github.com/prometheus/client_python to masu worker.

Potential collection items:
- Counters: providers processed (of type, per tenant)
- Error Counters: An error occurred during processing (of type, per tenant)
- Summary: Time duration for total and components of processing
- Info: Last status of all providers for all tenants

## Acceptance Criteria

- [ ] Able to view metrics in Grafana dashboard

**Comment by lcouzens** [comment]
Verified
Commit: d4de1a9035d4005a307d7116578f40b26f4d34f7
