### ISSUE TITLE
OCP on AWS data not displaying up to date data due to ingestion/summarization order

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#407]
**Describe the bug**
If AWS data is ingested before OCP data then the OCP on AWS summary table is blank by the time data is ingested and summarized

**To Reproduce**
1. Load and summarize AWS data
2. Load and summarize OCP data
3. Hit ocp on aws API endpoints

**Expected behavior**
That data should be up to date regardless of ingest order

**Comment by lcouzens** [comment]
Verified
Commit: 3d29fc6466fc14fc8372aef1995b6be498235d74
