### ISSUE TITLE
Convert OpenShift costs view to table

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#411]
## User Story
As a user I want OpenShift cost latency low so I can view the chart quickly.

## Assumptions
- The view can take a while to generate with larger data sets, seeing 20 second latency

## Implementation Details
- Remove the current view in koku and switch the model to a managed table
- Take the view SQL and translate it to update SQL

## Acceptance Criteria

- [ ] The current view has been removed
- [ ] A table is created 
- [ ] The summary updater updates this table
- [ ] API call latency is greatly reduced

**Comment by lcouzens** [comment]
Verified
Commit: b53e485d388918400671059e35aebc2de92d85d7
