### ISSUE TITLE
Clean summary tables for OCP-on-Cloud when removing a single provider in that setup

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#440]
**Describe the bug**
The `reports/openshift/infrastructures/aws/instance-types/` API is not updated when the OCP provider is removed from an OCP-on-AWS setup.  This is just one endpoint but there are likely other `openshift/infrastructures/aws` endpoints that have the same problem.

**To Reproduce**
1. Create providers and ingest data for OCP-on-AWS
2. Hit the `openshift/infrastructures/aws` endpoint to get a sample of the results.
3. Remove the OCP provider
4. Run the same `openshift/infrastructures/aws` endpoint and you will see it's the same as #2

**Expected behavior**
API should show 0 data

**Comment by lcouzens** [comment]
Verified
Commit: 27cf79ead6b17456269a62ee7a502a3725924e54
