### ISSUE TITLE
Move Kafka handler to new Masu Listener pod

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#444]
## User Story
The Kafka handler is currently running as a daemon thread in the masu worker.  In order to scale the workers and ensure temporary file locations are available for processing on the right pod we want to make the following changes:

1. Create a ingest listener pod which will listen to kafka (same as what's happening currently in the worker pod)
2. Instead of simply dropping the file downloaded from the upload service into a temporary staging directory we want to run the line item report processor on it immediately so the line item data is saved in the database.

## Impacts
masu ingest processing

## Assumptions
- Need to clarify whether or not a single listener can be running.  Concern I have: Since we could have multiple listeners subscribed to the same Kafka topic; then both listeners would be downloading/processing the same reports.

## Implementation Details
- It would be nice if the insights local temporary directory was clear after the listener processes the file.  We should keep the insights local directory so we can still side load Nise data and have the poller process pick up and process those changes.

## Acceptance Criteria

- [ ] OpenShift reports will continue to be handled by listening for Kafka messages on the upload service
- [ ] OpenShift reports are processed as soon as the payload is downloaded.

**Comment by lcouzens** [comment]
Verified
Commit: 4ce8120e0b8bf945fcb97c72656cc51465264104
