### ISSUE TITLE
Duplicating AWS data on ingestion

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#490]
**Describe the bug**
We appear to be duplicating AWS line items when we process a new manifest.

**To Reproduce**
1. Have a large manifest with multiple files that takes longer than an hour to run
2. Have the scheduler start another download/process task the next hour
3. Watch both tasks run and have some of the same report files processed multiple times.
4. Check provider endpoint's stats to see more files processed than in the manifest. 

**Expected behavior**
We should process a manifest only one time and any scheduled task that wakes up while processing should not trigger another download/process.

**Comment by adberglund** [comment]
@lcouzens This might be easiest to talk through, but this really happens for reports that have multiple files. Basically if you start a download on a manifest with 2+ files, and then turn around and download again, we should see that the 2nd download recognizes that the manifest has already been seen and does not download and process a 2nd time.

**Comment by lcouzens** [comment]
Verified
