### ISSUE TITLE
Track Customer Cost Usage Report Consumption

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#5]
## User Story
As user, I want to know how up-to-date my cost data is so that I can understand how current and reliable it is.

## Assumptions
We will initially be polling for updates, but may later move to SNS for Cost Usage Report availability.

## Implementation details

For each customer we need to capture the following data:

- Current _cost usage report_ being read
- Read Cursor (files are appended to; we don't need to start at the beginning)
- Last processing completed time
- Last processing started time

## Acceptance Criteria

- [ ] Verify that we can capture the processing complete time to show the "freshness" of the data.
- [ ] Verify the current cost usage report that was read
- [ ] Verify test coverage between stakeholders.

**Comment by dccurtis** [comment]
@chambridge This can probably be closed.  Looks like the story for `ReportStatsDBAccessor`.  Probably a left over dup from koku

**Comment by chambridge** [comment]
I've marked it as "ready to test" in case it was missed by QE, since this may have pre-dated that tag.

**Comment by dccurtis** [comment]
Closing, duplicate story
