### ISSUE TITLE
Reconcile report data when bill is finalized

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#54]
## User Story
As a koku user, I want cost and usage data in its finalized form when AWS produces a bill (after the billing period ends) so that I am not relying on estimates for periods of time that have been billed.

## Impacts
Back end

## Role
Back end engineer

## Assumptions
- Data processed during the billing period is considered an estimate
- Data with an invoice id in the cost usage report is finalized

## Implementation Details
- We will need to either update the rows in the database or purge the month's data and reprocess it entirely with the finalized data 
- This could be it's own scheduled celery task that checks at the end of a billing period and runs reconciliation

## Acceptance Criteria

- [ ] Verify that all data for prior billing periods have an invoice id

**Comment by lcouzens** [comment]
Verified
commit: "95005674814c755e1b1865a3b2b751c9b97f10ca"
