### ISSUE TITLE
Download and process CUR from AWS (synchronously)

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#57]
## User Story
As user, I want my CUR stored in AWS to be downloaded and stored in in the Koku/Masu database for further analysis

## Assumptions
AWS account is properly configured

## Implementation details
As an initial step we want to synchronously download and store CUR data with Masu.  There will be a test end point for Masu that will kick off the download/processing.  In a subsequent user story we will make this action be asynchronous and processing/downloads will be continuously happening.

## Acceptance Criteria

- [ ] Verify that a CUR will be downloaded and stored in the Koku database by hitting the test end point /api/v1/download.

**Comment by dccurtis** [comment]
https://github.com/project-koku/masu/pull/56

**Comment by LandoCalrizzian** [comment]
VERIFIED. Hitting /download will trigger a sync of AWS reports
