### ISSUE TITLE
Enable multiple workers to handle customer usage report processing

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#6]
## User Story

As developer, I want to engineer the customer usage report processing to enable multiple worker so that data is processed as quickly as possible to support multiple customers using the service.

## Assumptions

We will likely utilize [Celery](http://www.celeryproject.org/) to process the cost usage reports (CUR) on top of RabbitMQ.

## Implementation details

Workers will wake up on a regular basis and check Customer S3 buckets for new CURs.
We need to track what reports have been processed, what reports are being processed, and have a strategy for managing if a worker goes down during processing that the CUR doesn't go unprocessed.

## Acceptance Criteria

- [ ] Verify that multiple workers spin up and handle different customer usage reports and a record is kept of the processing of these reports
- [ ] Verify that if a worker is brought down during processing of a CUR that processing of the CUR is picked up by another worker.

**Comment by LandoCalrizzian** [comment]
@chambridge @blentz Should we move this to the backlog until there is a fix/workaround/refactor for allowing multiple workers on OSD?

**Comment by chambridge** [comment]
This should be testable now.

**Comment by lcouzens** [comment]
Verified
Commit: 4d67ef8cbc2f2a3c5dd0ff2505551903631d8620

Scaled to 2 workers, added providers/watched logs share ingestion.
