### ISSUE TITLE
Create endpoint to handle an SNS request

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#66]
Add an API endpoint that will handle an SNS update of a customers cost and usage report data.

Its expected that the message will contain the bucket information and they key to report definition (i.e. manifest file)

______
Associated with: https://github.com/project-koku/masu/issues/7

**Comment by chargio** [comment]
It is possible to test the connection? Send some message to the SNS queue in our applicaiton to verify that everything has been configured properly
