### ISSUE TITLE
Trigger workers to process via SNS

### ISSUE THREAD

**Issue by adberglund** [project-koku/masu#7]
## User Story

As a developer, I want workers to be triggered to process cost usage reports as quickly as possible by utilizing Amazon's SNS notifications on S3 bucket changes so that data is available to customers in a timely fashion and as a better strategy than polling alone.

## Assumptions
The IAM policy that the customer enables on their AWS account provides the capability to setup SNS notifications of changes to the S3 bucket.

## Implementation details
We will have listeners for SNS events on customer S3 buckets. Similar to the polling procedure this will cause a worker to process the CUR and note its completion

## Acceptance Criteria

- [ ] Verify that an SNS event for a new customer usage report triggers a worker to process the new data.

**Comment by dccurtis** [comment]
This functionality was delivered with PR #73
