### ISSUE TITLE
Investigate SNS Policy

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#75]
With PR #73, Masu will become a AWS SNS Topic HTTP end point.  There needs to be some thought and investigation into how we should setup the Service Provider (our) AWS account and Topic such that customers can configure their S3 bucket to notify our Topic when CUR updates occur.

This could be as simple as making the prefix of the bucket name pass the Topic policy test, or we could programmatically update our policy when the provider is added in Koku to give access to the bucket name the user is providing.

**Comment by dccurtis** [comment]
Don't forget to update Koku SNS configuration check to be more strict to conform to the policy decision decided on by this investigation.

https://github.com/project-koku/koku/pull/265

**Comment by chambridge** [comment]
Needed for Q4
