### ISSUE TITLE
Update 'Read the Docs' to include SNS setup

### ISSUE THREAD

**Issue by dccurtis** [project-koku/masu#80]
Document updates should include how to setup the S3 bucket to send notifications to a SNS Topic configured by the Koku/Masu service administrator.

**Comment by dccurtis** [comment]
Adding #75 as a dependency since we the outcome o the SNS Policy configuration investigation will drive how the setup should be documented.

**Comment by chambridge** [comment]
I had created the following for the docs. Since the content is in koku:
https://github.com/project-koku/koku/issues/244

**Comment by dccurtis** [comment]
Ok sounds good.  I'll close this
