### ISSUE TITLE
Convert AWS region strings to easy filtered search

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#85]
## User Story
As user, I want to be able to filter cost usage data by region so that can see a subset of cost or usage.

## Impacts
Backend

## Role
User

## Assumptions
- This applies to AWS Cost Usage processing only

## Implementation Details
Currently regions within the cost usage reports may be recorded as the following "US East (N. Virginia)". This doesn't lend it self to easily searched data with the UI and does not line up as simple with the availability zones which are `us-east-1`.  When processing the CSV data we should convert the region data to a shorter/simplified form of `us-east`

## Acceptance Criteria

- [ ] Region data is stored in a simpler format; "US East (N. Virginia)" --> "us-east"

**Comment by LandoCalrizzian** [comment]
VERIFIED. I was able to filter based on region/avail_zone without grouping
